services:
  db:
    image: postgres:15-alpine
    container_name: pet_hotel_db_prod
    # Carrega variáveis de produção
    env_file:
      - .env.prod
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    networks:
      - app-network-prod
    restart: always

  api:
    build: .
    container_name: pet_hotel_api_prod
    # Carrega variáveis de produção
    env_file:
      - .env.prod
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: always
    networks:
      - app-network-prod

volumes:
  postgres_data_prod:

networks:
  app-network-prod:
    driver: bridge